### ISSUE TITLE
Automatic schema optional?

### ISSUE THREAD

**Issue by dukedougal** [pudo/dataset#133]
The documentation says:

Automatic schema: If a table or column is written that does not exist in the database, it will be created automatically.

It would be good if this was optional (ideally off by default).  It would make it too easy to unintentionally modify the database structure which I'd really prefer didn't happen.

**Comment by pudo** [comment]
Automatic schema creation is kind of the point of dataset, it's why most people use it. Otherwise it'd just be SQLAlchemy core - which is a perfectly good alternative if you want more fine-grained control over the query construction.

For what it's worth, you can also call dataset like this to disable column creation: 

```python
table.insert(data, ensure=False)
```

**Comment by krkhnh** [comment]
I second dukedougal's opinion. 'Automatic schema creation' is powerful. But the point here is 'unintentionally'. What if I mistype a column name of a table with millions of rows? Changing the default value to 'False' would be less annoying.

**Comment by pudo** [comment]
@krkhnh: I hear you. Changing the default would literally break any script written with ``dataset``. Would it make sense to turn it into a per-session flag? Would you perhaps be interested in trying your hand on a PR?

**Comment by krkhnh** [comment]
It's my first PR(it's 'Pull Request', right?), but here goes nothing.
