### ISSUE TITLE
Parallel Insertions using MultiProcessing Library

### ISSUE THREAD

**Issue by rashoodkhan** [pudo/dataset#159]
I ran the following script - https://gist.github.com/rashoodkhan/66ce67a80009c36dde86

Which essentially creates some dummy data and pushes it into MySQL Database using Dataset library. If I run the script with only one thread pool, it works perfectly fine, but when the pool size is increased for parallel execution something weird happens; only a partial data is inserted.

I did this because, I need to fetch some data from a web API and insert in to our database. I usually use a Pool for faster execution of fetching the data from the web. Does dataset not support parallel uploads? Or am I doing something wrong?

Btw, I love the dataset library! It has made my work so much easier with database. Kudos! :+1:

**Comment by pudo** [comment]
hey @rashoodkhan - there's nothing in ``dataset`` itself which would prevent using it with the multiprocessing library, although I usually use threading instead of actual worker processes. It may be worth checking out the sqlalchemy [documentation on connection pooling](http://docs.sqlalchemy.org/en/latest/core/pooling.html) to see if they note any issues. As a first debug step, I'd move the declarations of ``DB`` and ``TABLE`` into the insertIntoDb function - not sure the database handles survive the ``fork()``.
