### ISSUE TITLE
can't truncate table using query()

### ISSUE THREAD

**Issue by ryantuck** [pudo/dataset#178]
```python
for row in db.query('select * from my_table'):
    print row # (a bunch of rows returned)

db.query('truncate table my_table')

for row in db.query('select * from my_table'):
    print row # (a bunch of rows returned again!)
```

This is weird behavior. I can confirm that both `create` and `drop` do work as expected, but `truncate` doesn't.

**Comment by ryantuck** [comment]
current workaround is:

```python
table = db.load_table('my_table')
table.delete()
```

**Comment by pudo** [comment]
I've just tried this out, and I can reproduce the issue with postgresql 9.4. (Which DBMS are you using?) However, I can't really tell if this is due to a database permissions issue or the Python bindings. It does, however, also fail to ``TRUNCATE`` when using the underlying database bindings (``sqlalchemy.core``) separately, which leads me to believe that it may be a permissions issue. If you find out more, it might be worth filing an issue with SQLAlchemy: https://bitbucket.org/zzzeek/sqlalchemy
