### ISSUE TITLE
Use sqlite_autoincrement for SQLite data bases?

### ISSUE THREAD

**Issue by Macuyiko** [pudo/dataset#207]
Currently, the auto increment implementation of SQLAlchemy and SQLite will cause SQLite to reuse earlier-seen IDs in case rows are deleted. The auto-generated id is hence MAX(id) + 1, instead of LAST_ID_GENERATED + 1.  This can cause issues when working with multiple tables with some kind of "weak" foreign key system going on.

SQLAlchemy supports setting the "sqlite_autoincrement" parameter to add AUTOINCREMENT when creating tables. Perhaps this can be added as an option to dataset?

**Comment by pudo** [comment]
It looks like [the SQLite documentation discourages](https://sqlite.org/autoinc.html) the use of the AUTOINCREMENT without a good reason to do so. Unless you can describe the issues which you are encountering in some detail, my preference would be not to use this option. Are you guessing primary key IDs?

**Comment by Macuyiko** [comment]
That's right, it's discouraged, though sometimes still helpful (indeed in the case of primary IDs).

Image the following: table A inserts rows with ids 1, 2, 3. Table B has rows referring to table A, so some_foreign_id = 3.

Now row 3 gets deleted from table A. Later on, a new row gets inserted. This new row will get id = MAX(tableA.id)+1 = 3. Table B now has information referring to this row even while it should not. AUTOINCREMENT would assign id=4 to the new row in table A. Table B would then still contain a row referring to 3, though this can be easily regarded as "stale" information (row 3 does not exist anymore) without having to manually delete it.

**Comment by pudo** [comment]
I'm sorry to be a little bit intransigent here, but let me say this: if you need to make guarantees about foreign keys, it's a 100% sign you have outgrown the modest scope of ``dataset`` and you need to start using a real ORM. The point of dataset is to dump some scraped data in a database quick (or similar, ad-hoc data processing stuff), and we've rejected the notion of supporting FKs multiple times, simply because it's complex and would make it into SQLAlchemy proper.

So, yes, we can add a toggle for this. But please, please be careful about whether your actual problem is PK re-use or a more broad lack of referential integrity (and DELELTE CASCADEs).

**Comment by Macuyiko** [comment]
That's fair, though I've regularly encountered simple setups (e.g. using dataset for a quick scraping data capture job) where the notion of FK's would be rather helpful.

**Comment by void4** [comment]
It would be very useful to have this as an option, I agree that this tends to happen in use cases which should use more sophisticated db handlers, but it would be nice to have anyway.
