### ISSUE TITLE
Database _check_ensure method overrides Table ensure keyword argument

### ISSUE THREAD

**Issue by emanuelfeld** [pudo/dataset#225]
If ensure is not set for a Table operation, its value is set to the Database ensure_schema value. With ensure_schema set to True by default, new columns are added if ensure is not set to False.

https://github.com/pudo/dataset/blob/da901efbf747c1e2863d5a14982191aea3ca105e/dataset/table.py#L280

This is not the expected behavior from reading the API documentation

> If ensure is set, any of the keys of the row are not table columns, they will be created automatically.

It would be clearer if the default argument for ensure was True.

**Comment by pudo** [comment]
Ok, this is pretty confusing, please bear with me :) 

The reason the ``ensure`` arguments to the individual methods (like ``insert``) are ``None`` is to allow for the database-level override. It's basically a sentinel to use whatever value the global setting has.

I'd suggest making this clearer in the docs, rather than discarding the global default (which is the only way to make dataset not mess with your schema, basically to put it in safe mode...).

**Comment by emanuelfeld** [comment]
Sounds fine to me. Docs just need to clarify that `ensure` overrides the database `ensure_schema` setting.
