### ISSUE TITLE
Where does the database save the data?

### ISSUE THREAD

**Issue by eduaero** [pudo/dataset#232]
Thank you very much for reading my comment.
I was wondering how do I define where I save the database in local. I was using this line of code, but I cannot find where it gets save.

db = dataset.connect('sqlite:///:memory:')

I would like to save it on \db on the same folder where I run the codes.

Thank you very much!!

Congrats for such an amazing and wonderful project!! I LOVE IT!!

Edu

**Comment by RcrdBrt** [comment]
> `db = dataset.connect('sqlite:///:memory:')`
That line creates an in-memory sqlite database. In order to select a non-temporary location you must provide a path in the initialization URL like this:
`sqlite:///relative/path/to/file.db
sqlite:////absolute/path/to/file.db`.

For more informations and a helper on URL building, see [here](http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.engine.url.URL).

**Comment by eduaero** [comment]
Thank you very much!!
It was really useful :)

**Comment by eduaero** [comment]
Thank you very much!!
It was really useful :)
