### ISSUE TITLE
Support for Foreign Keys and relationships

### ISSUE THREAD

**Issue by jgburd79** [pudo/dataset#322]
Is there support for Foreign Keys? How does one normalize the database and create relationships?

**Comment by pudo** [comment]
It's always been a sort of magic line for us: if the schema you are doing is complex enough that foreign keys are a good idea, you need to start using a proper ORM instead of `dataset`. Foreign keys and relationships bring with them a whole different level of need for metadata, and I don't know how it could be made to behave like "just a dict"...

**Comment by jgburd79** [comment]
I figured as much since there wasn't anything in the documentation but thought I would ask anyway. I think I can kind of do it manually. I will have to see what I can get to work.
