### ISSUE TITLE
inconsistent Upsert documentation

### ISSUE THREAD

**Issue by matecsaj** [pudo/dataset#404]
Upserts are a feature here: https://dataset.readthedocs.io/en/latest/

And then a limitation here: https://dataset.readthedocs.io/en/latest/quickstart.html#limitations-of-dataset

Which is it? Please make the documentation consistent.

**Comment by RedContritio** [comment]
the later said "Database-native UPSERT semantics", and current version combine `insert` and `update` to realize `upsert`, so it's a feature, but not native.

**Comment by pudo** [comment]
The problem is that we never really forced making a unique index for upsert key sets in the dataset Python API, which is needed for doing it in Postgres (and SQLite?). To migrate from one to the other, we'd end up implicitly creating constraints on a database, which feels like a really icky thing to do. 

It's left me personally choosing to do Postgres upserts manually in a lot of my newer apps rather than using dataset :/ (e.g.: https://github.com/opensanctions/storyweb/blob/main/storyweb/logic/articles.py#L156-L164 )

**Comment by matecsaj** [comment]
Thanks all for remedying my confusion and making this great library available. 

I'd like to suggest two documentation changes.

1. Link all limitations to their [relevant item](https://github.com/pudo/dataset/issues/317) in the issue list.

Why? Readers can learn more without bothering you with a question that already has an answer.

3. Have two limitation lists, one functional and one performance. 

Why? Readers that don't require high performance will be more likely to use your library.
