### ISSUE TITLE
More searchable name

### ISSUE THREAD

**Issue by bbergmann** [pudo/dataset#7]
I'm taking a hard look at dataset, but I found after I had misplaced my link to dataset that the terms I was using to search for dataset in google were not leading me back despite several variations. This is an interesting project. I hope it can be more easily found.

**Comment by beasteers** [comment]
Super sorry about commenting on such an old thread, but I do want to say that as a user that loves this package, the generic name makes it near impossible to search for specific/auxiliary docs or troubleshooting (SO questions and others) in google. Whenever I search something more specific than `python dataset`, I end up getting a page of pandas, sklearn, and other unrelated docs. (though when I search only `python dataset` it's the first 2 so that's good)

I don't mind the generic name in and of itself, but I do wish there was another name to search that would filter out irrelevant results. Seeing as it's a mature package, I understand that there may not be much to be done, but it is a usability issue.
